
services:

  tomcat-container:
    container_name: tomcat-container
    image: tomcat:8.5.70-jre8
    environment:
      - TOMCAT_USERNAME=jla
      - TOMCAT_PASSWORD=jla2012
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps  
      - ./tomcat/logs:/usr/local/tomcat/logs
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      
    ports:
      - 80:8080
      - 443:8443
    restart: always

