version: '3.4'

services:

  tomcat-container:
    container_name: tomcat-container
    image: tomcat:8.5.70-jre8
    environment:
      - TOMCAT_USERNAME=x
      - TOMCAT_PASSWORD=x
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps  
      - ./tomcat/conf:/usr/local/tomcat/conf
      - ./tomcat/logs:/usr/local/tomcat/logs
      
    ports:
      - 80:8080
      - 443:8443
    restart: always

